# N_SERVICES = 63 (~p90 SL)
- app: synthetic_app1
  db_accesses: 7    # median  SF
  call_depth: 6     # median  CD
  out_degree: 2     # median  FO
  entrypoints: 1

# N_SERVICES = 63 (~p90 SL)
- app: synthetic_app2
  db_accesses: 55   # p90     SF
  call_depth: 6     # median  CD
  out_degree: 2     # median  FO
  entrypoints: 1

# N_SERVICES = 4095
- app: synthetic_app3
  db_accesses: 7    # median  SF
  call_depth: 12    # p90     CD
  out_degree: 2     # median  FO
  entrypoints: 1

# N_SERVICES = 9331
- app: synthetic_app4
  db_accesses: 7    # median  SF
  call_depth: 6     # median  CD
  out_degree: 6     # p75     FO
  entrypoints: 1

# N_SERVICES = 63
- app: synthetic_app5
  db_accesses: 7    # median  SF
  call_depth: 6     # median  CD
  out_degree: 2     # median  FO
  entrypoints: 10000 # 10k requests


