# TOTAL = 2.3852
- app: synthetic_app1
  db_accesses: 20 # p90 Alibaba
  call_depth: 20 # max. Alibaba
  out_degree: 1
  entrypoints: 1

# TOTAL = 3.9688s
- app: synthetic_app2
  db_accesses: 8 # p50 Alibaba (+/- looking at the graph)
  call_depth: 4 # avg Alibaba
  out_degree: 3 # p50 Alibaba  (+/- looking at the graph)
  entrypoints: 1

# TOTAL = 8.7352s
- app: synthetic_app3
  db_accesses: 20 # p90 Alibaba
  call_depth: 4 # avg Alibaba
  out_degree: 5 # p90 Alibaba
  entrypoints: 1

# TOTAL = 14.3589s
- app: synthetic_app4
  db_accesses: 20 # p90 Alibaba
  call_depth: 200 # 10x max. Alibaba
  out_degree: 1
  entrypoints: 1

# TOTAL = 25.7232s
- app: synthetic_app5
  db_accesses: 20 # p90 Alibaba
  call_depth: 350  # 10x max. (Uber 35, Alibaba 20)
  out_degree: 1
  entrypoints: 1
