#- app: synthetic_app2
#  description: 30x avg. fan-out
#  call_depth: 1
#  out_degree: 375

- app: synthetic_app3
  #description: ALIBABA: p50 stateful (8), avg. call depth (4.27), p50 fanout (3)
  call_depth: 4
  out_degree: 3
  db_accesses: 8
  entrypoints: 1

#- app: synthetic_app4
#  description: UBER: avg. rpc depth (8.5), avg total rpc (112)
