# num_services = 1 + 3 + 9 + 27 + 81 = 121
- app: synthetic_app
  call_depth: 1
  out_degree: 100

- app: synthetic_appA
  call_depth: 9
  out_degree: 1

- app: synthetic_appB
  call_depth: 1
  out_degree: 9

# num_services = 1 + 3 + 9 + 27 + 81 = 121
- app: synthetic_app1
  call_depth: 4
  out_degree: 3

# num_services = 1 + 3 + 6 + 9 + 27 + 81 = 127
- app: synthetic_app2
  call_depth: 5
  out_degree: 3

# num_services = 1 + 1 + 1 ... = 121
- app: synthetic_app3
  call_depth: 340
  out_degree: 1

# num_services = 1 + 4 + 16 + 64 + 256 = 341
- app: synthetic_app4
  call_depth: 4
  out_degree: 4

# num_services = 1 + 120 = 121
- app: synthetic_app5
  call_depth: 1
  out_degree: 340

# num_services = 1 + 5 + 25 + 125 + 625 = 781
- app: synthetic_app6
  call_depth: 4
  out_degree: 5

# num_services = 1 + 4 + 16 + 64 + 256 + 1024 = 1365
- app: synthetic_app7
  call_depth: 5
  out_degree: 4
