# N_SERVICES = 63
- app: synthetic_app1
  #rpcs: 6          # median  SL
  db_accesses: 7    # median  SF
  call_depth: 6     # median  CD
  out_degree: 2     # median  FO
  entrypoints: 1

# N_SERVICES = 63
- app: synthetic_app2
  #rpcs: 6          # median  SL
  db_accesses: 309  # p99     SF
  call_depth: 6     # median  CD
  out_degree: 2     # median  FO
  entrypoints: 1

# N_SERVICES = 131.071
- app: synthetic_app3
  #rpcs: 6          # median  SL
  db_accesses: 7    # median  SF
  call_depth: 17    # p99     CD
  out_degree: 2     # median  FO
  entrypoints: 1

# N_SERVICES = 1.962.169
- app: synthetic_app4
  #rpcs: 6          # median  SL
  db_accesses: 7    # median  SF
  call_depth: 6     # median  CD
  out_degree: 72    # p99     FO
  entrypoints: 1

# N_SERVICES = 18.764.998.447.376
- app: synthetic_app5
  #rpcs: 6          # median  SL
  db_accesses: 55   # p90     SF
  call_depth: 12    # p90     CD
  out_degree: 16    # p90     FO
  entrypoints: 1

# N_SERVICES = 63
- app: synthetic_app6
  #rpcs: 6          # median  SL
  db_accesses: 7    # median  SF
  call_depth: 6     # median  CD
  out_degree: 2     # median  FO
  entrypoints: 10000 # 10k requests


