- app: synthetic_app1
  db_accesses: 20 # p90 Alibaba
  call_depth: 4   # avg Alibaba
  out_degree: 3   # p50 Alibaba  (+/- looking at the graph)
  entrypoints: 1

- app: synthetic_app2
  db_accesses: 20 # p90 Alibaba
  call_depth: 4   # avg Alibaba
  out_degree: 5   # p90 Alibaba
  entrypoints: 1

- app: synthetic_app3
  db_accesses: 20   # p90 Alibaba
  call_depth: 350   # 10x max. Uber
  out_degree: 1
  entrypoints: 1

- app: synthetic_app4
  db_accesses: 100  # 10x p90 Alibaba
  call_depth: 350   # 10x max. Uber
  out_degree: 1
  entrypoints: 1

- app: synthetic_app5
  db_accesses: 20 # p90 Alibaba
  call_depth: 4   # avg Alibaba
  out_degree: 3   # p50 Alibaba  (+/- looking at the graph)
  entrypoints: 500
